#path principal
server.port=8090
server.servlet.context-path=/laMaderera

#view resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/almacen_ventas?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
